// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RoadDefect.Api.Data;

#nullable disable

namespace RoadDefect.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129160828_SeedAll")]
    partial class SeedAll
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoadDefect.Api.Models.Area", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("GeoJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ParentAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentAreaId");

                    b.ToTable("Areas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Area 1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Area 2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Area 3"
                        });
                });

            modelBuilder.Entity("RoadDefect.Api.Models.Defect", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId1")
                        .HasColumnType("int");

                    b.Property<int?>("AssignedEngineerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefectType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("ReportedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoadSegmentId")
                        .HasColumnType("int");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AreaId1");

                    b.HasIndex("AssignedEngineerId");

                    b.HasIndex("ReportedByUserId");

                    b.HasIndex("RoadSegmentId");

                    b.ToTable("Defects");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.DefectImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefectId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBeforeRepair")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("DefectId");

                    b.ToTable("DefectImages");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.RoadSegment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaId")
                        .HasColumnType("int");

                    b.Property<int?>("AreaId1")
                        .HasColumnType("int");

                    b.Property<double>("EndLat")
                        .HasColumnType("float");

                    b.Property<double>("EndLng")
                        .HasColumnType("float");

                    b.Property<int>("FunctionalClass")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("StartLat")
                        .HasColumnType("float");

                    b.Property<double>("StartLng")
                        .HasColumnType("float");

                    b.Property<int>("TrafficImportance")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("AreaId1");

                    b.ToTable("RoadSegments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AreaId = 1,
                            EndLat = 20.600000000000001,
                            EndLng = 78.969999999999999,
                            FunctionalClass = 1,
                            Name = "Main Highway - Section 1",
                            StartLat = 20.593699999999998,
                            StartLng = 78.962900000000005,
                            TrafficImportance = 3
                        },
                        new
                        {
                            Id = 2,
                            AreaId = 2,
                            EndLat = 20.510000000000002,
                            EndLng = 78.915000000000006,
                            FunctionalClass = 2,
                            Name = "City Ring Road - East",
                            StartLat = 20.5,
                            StartLng = 78.900000000000006,
                            TrafficImportance = 2
                        },
                        new
                        {
                            Id = 3,
                            AreaId = 3,
                            EndLat = 20.552499999999998,
                            EndLng = 78.952500000000001,
                            FunctionalClass = 3,
                            Name = "Market Street Lane",
                            StartLat = 20.550000000000001,
                            StartLng = 78.950000000000003,
                            TrafficImportance = 1
                        });
                });

            modelBuilder.Entity("RoadDefect.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AreaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AreaId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 99,
                            CreatedAt = new DateTime(2025, 11, 29, 16, 8, 27, 987, DateTimeKind.Utc).AddTicks(2899),
                            Email = "admin@roaddefect.com",
                            IsActive = true,
                            Name = "Super Admin",
                            PasswordHash = "E86F78A8A3CAF0B60D8E74E5942AA6D86DC150CD3C03338AEF25B7D2D7E3ACC7",
                            Phone = "9999999999",
                            Role = 2
                        });
                });

            modelBuilder.Entity("RoadDefect.Api.Models.WorkOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("DefectId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DefectId")
                        .IsUnique();

                    b.ToTable("WorkOrders");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.WorkOrderUpdate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("UpdatedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("WorkOrderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UpdatedByUserId");

                    b.HasIndex("WorkOrderId");

                    b.ToTable("WorkOrderUpdates");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.Area", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.Area", "ParentArea")
                        .WithMany()
                        .HasForeignKey("ParentAreaId");

                    b.Navigation("ParentArea");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.Defect", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadDefect.Api.Models.Area", null)
                        .WithMany("Defects")
                        .HasForeignKey("AreaId1");

                    b.HasOne("RoadDefect.Api.Models.User", "AssignedEngineer")
                        .WithMany()
                        .HasForeignKey("AssignedEngineerId");

                    b.HasOne("RoadDefect.Api.Models.User", "ReportedByUser")
                        .WithMany()
                        .HasForeignKey("ReportedByUserId");

                    b.HasOne("RoadDefect.Api.Models.RoadSegment", "RoadSegment")
                        .WithMany("Defects")
                        .HasForeignKey("RoadSegmentId");

                    b.Navigation("Area");

                    b.Navigation("AssignedEngineer");

                    b.Navigation("ReportedByUser");

                    b.Navigation("RoadSegment");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.DefectImage", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.Defect", "Defect")
                        .WithMany("Images")
                        .HasForeignKey("DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.RoadSegment", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadDefect.Api.Models.Area", null)
                        .WithMany("RoadSegments")
                        .HasForeignKey("AreaId1");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.User", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.Area", "Area")
                        .WithMany()
                        .HasForeignKey("AreaId");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.WorkOrder", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.User", "AssignedToUser")
                        .WithMany()
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadDefect.Api.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadDefect.Api.Models.Defect", "Defect")
                        .WithOne("WorkOrder")
                        .HasForeignKey("RoadDefect.Api.Models.WorkOrder", "DefectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("Defect");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.WorkOrderUpdate", b =>
                {
                    b.HasOne("RoadDefect.Api.Models.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoadDefect.Api.Models.WorkOrder", "WorkOrder")
                        .WithMany("Updates")
                        .HasForeignKey("WorkOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UpdatedByUser");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.Area", b =>
                {
                    b.Navigation("Defects");

                    b.Navigation("RoadSegments");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.Defect", b =>
                {
                    b.Navigation("Images");

                    b.Navigation("WorkOrder");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.RoadSegment", b =>
                {
                    b.Navigation("Defects");
                });

            modelBuilder.Entity("RoadDefect.Api.Models.WorkOrder", b =>
                {
                    b.Navigation("Updates");
                });
#pragma warning restore 612, 618
        }
    }
}
